server:
  port: 8460
spring:
  application:
    name: search-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  jackson:
    default-property-inclusion: NON_NULL
  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: changeme
  