server:
  port: 8440
spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 50MB
  datasource:
    url: jdbc:mysql://localhost:3306/oasys?serverTimezone=UTC&useSSL=false
    username: root
    password: 136623
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: NON_NULL
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis:
  mapper-locations: classpath:mapper/*.xml
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  file-bucket-name: files
  profile-picture-bucket-name: profile-pictures