server:
  port: 8430
spring:
  application:
    name: attendance-service
  datasource:
    url: jdbc:mysql://localhost:3306/oasys?serverTimezone=UTC&useSSL=false
    username: root
    password: 136623
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: NON_NULL
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
mybatis:
  mapper-locations: classpath:mapper/*.xml